import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

export default strings = new LocalizedStrings({
    "en-US": {
        screen_title_1: "Personal Assistant",
        screen_desc_1: "The UrbanBlue system helps you to maintain the ecological balance and well-being of animals and plants on high-tech farms.",
        screen_title_2: "Get Notified",
        screen_desc_2: "Your virtual assistant flags potential irregularities and alerts you before damage is done.",
        screen_title_3: "Helping Hand",
        screen_desc_3: "Your new digital friend offers you a helping hand to resolve detected issues in good time.",
        screen_title_4: "Teamwork",
        screen_desc_4: "If something requires the attention of others, inform your team immediately with a simple one-click alarm.",
        screen_title_5: "Let me help",
        screen_desc_5: "Allow the AI-empowered UrbanBlue assistant to notify you about potential irregularities and system status updates.",
        give_perm: "Give permission",
        next: "Next",
        validation_email: "The e-mail field can't be empty.",
        validation_password: "The password field can't be empty.",
        slogan: "Intelligence working alongside",
        email_placeholder: "Your email address",
        pass_placeholder: "Your password",
        LogIn: "Login",
        Loading: "LOADING",
        forget_pass: "Forgot password?",
        no_account: "Don’t have an account yet?",
        contact: "Contact us",
        password: "Password",
        dashboard_title: "Status Overview",
        Important: "Important",
        Other: "More",
        More: "Other",
        More_Desc: "Use this option to write a comment.",
        dashboard_desc: "The monitored areas and systems are operating as expected.",
        dashboard_note: "Note: You will receive a notification and updates here if anything needs urgent attention.",
        time_escalate: "Potential damage in",
        time_action: "Time to resolve the situation",
        time_watchlist: "Change expected within",
        sec: "sec",
        hide: "Hide",
        show: "Show",
        search: "Search for a situation, event type or status.",
        hours_ago: "hours ago",
        mins_ago: "min ago",
        location: "LOCATION",
        detail_screen_action_title: "Please mark the performed tasks.",
        img: "IMAGE",
        add_pic: "Add picture",
        alarm: "FALSE ALARM",
        alarm_desc: "Please mark in case of a false alarm.",
        resolve: "Resolve issue",
        req_alert_title: "WHAT SITUATION NEEDS TO BE RESOLVED?",
        req_alert_msg_placeholder: "Please indicate why you are alerting the team and, if possible, include a picture of the problem. For example: I cannot manage the matter alone, the measures taken do not solve the problem, something is broken that needs to be repaired, etc.",
        confirm: "Confirm",
        alert_team: "Alert team",
        req_res_title: "HOW WAS THE PROBLEM SOLVED?",
        req_res_placeholder: "Please describe briefly what you have done to improve the situation.",
        req_esc_title: "WHAT SITUATION NEEDS TO BE RESOLVED?",
        req_esc_desc: "Please indicate why you need to alert the team and, if possible, include a picture of the issue. For example: I cannot deal with the matter alone and need someone to help me, the measures taken do not solve the problem, something is broken that needs to be repaired, etc.",
        logout_title: "Would you like to log out?",
        logout_desc: "We can’t notify you with things that need your attention if you do.",
        log_out: "Log out",
        cancel: "Cancel",
        history: "History",
        recover_desc: "Please enter your email address to receive an email to restore your account.",
        recover_mail: "Send recovery email",
        action_req: "Action required",
        escalated: "Escalated",
        watchlist: "Watchlist",
        action_perf: "Action performed",
        active_opp: "Active Operation",
        default_op: "Default operation",
        inactive: "Inactive",
        active: "Activated",
        comment: "Comment",
        change_ongoing: "Change Ongoing",
        net_error: "An error occurred.",
        invalid_add: "Email or password is incorrect.",
        other_desc: "Currently there is nothing to see here.",
        measure: "Measurements",

        current: "Current",
        sensor_title: "Sensors Overview",
        sensor_desc: "No devices available",
        sensor_note: "Log in the admin screen on your desktop and add  a device"
    },
    en: {
        screen_title_1: "Personal Assistant",
        screen_desc_1: "The UrbanBlue system helps you to maintain the ecological balance and well-being of animals and plants on high-tech farms.",
        screen_title_2: "Get Notified",
        screen_desc_2: "Your virtual assistant flags potential irregularities and alerts you before damage is done.",
        screen_title_3: "Helping Hand",
        screen_desc_3: "Your new digital friend offers you a helping hand to resolve detected issues in good time.",
        screen_title_4: "Teamwork",
        screen_desc_4: "If something requires the attention of others, inform your team immediately with a simple one-click alarm.",
        screen_title_5: "Let me help",
        screen_desc_5: "Allow the AI-empowered UrbanBlue assistant to notify you about potential irregularities and system status updates.",
        give_perm: "Give permission",
        next: "Next",
        validation_email: "The e-mail field can't be empty.",
        validation_password: "The password field can't be empty.",
        slogan: "Intelligence working alongside",
        email_placeholder: "Your email address",
        pass_placeholder: "Your password",
        LogIn: "Login",
        Loading: "LOADING",
        forget_pass: "Forgot password?",
        no_account: "Don’t have an account yet?",
        contact: "Contact us",
        password: "Password",
        dashboard_title: "Status Overview",
        Important: "Important",
        Other: "More",
        More: "Other",
        More_Desc: "Use this option to write a comment.",
        dashboard_desc: "The monitored areas and systems are operating as expected.",
        dashboard_note: "Note: You will receive a notification and updates here if anything needs urgent attention.",
        time_escalate: "Potential damage in",
        time_action: "Time to resolve the situation",
        time_watchlist: "Change expected within",
        sec: "sec",
        hide: "Hide",
        show: "Show",
        search: "Search for a situation, event type or status.",
        hours_ago: "hours ago",
        mins_ago: "min ago",
        location: "LOCATION",
        detail_screen_action_title: "Please mark the performed tasks.",
        img: "IMAGE",
        add_pic: "Add picture",
        alarm: "FALSE ALARM",
        alarm_desc: "Please mark in case of a false alarm.",
        resolve: "Resolve issue",
        req_alert_title: "WHAT SITUATION NEEDS TO BE RESOLVED?",
        req_alert_msg_placeholder: "Please indicate why you are alerting the team and, if possible, include a picture of the problem. For example: I cannot manage the matter alone, the measures taken do not solve the problem, something is broken that needs to be repaired, etc.",
        confirm: "Confirm",
        alert_team: "Alert team",
        req_res_title: "HOW WAS THE PROBLEM SOLVED?",
        req_res_placeholder: "Please describe briefly what you have done to improve the situation.",
        req_esc_title: "WHAT SITUATION NEEDS TO BE RESOLVED?",
        req_esc_desc: "Please indicate why you need to alert the team and, if possible, include a picture of the issue. For example: I cannot deal with the matter alone and need someone to help me, the measures taken do not solve the problem, something is broken that needs to be repaired, etc.",
        logout_title: "Would you like to log out?",
        logout_desc: "We can’t notify you with things that need your attention if you do.",
        log_out: "Log out",
        cancel: "Cancel",
        history: "History",
        recover_desc: "Please enter your email address to receive an email to restore your account.",
        recover_mail: "Send recovery email",
        action_req: "Action required",
        escalated: "Escalated",
        watchlist: "Watchlist",
        action_perf: "Action performed",
        active_opp: "Active Operation",
        default_op: "Default operation",
        inactive: "Inactive",
        active: "Activated",
        comment: "Comment",
        change_ongoing: "Change Ongoing",
        net_error: "An error occurred.",
        invalid_add: "Email or password is incorrect.",
        other_desc: "Currently there is nothing to see here.",
        measure: "Measurements",

        current: "Current",
        sensor_title: "Sensors Overview",
        sensor_desc: "No devices available",
        sensor_note: "Log in the admin screen on your desktop and add  a device"
    },
    de: {
        screen_title_1: "Persönlicher Assistent",
        screen_desc_1: "Das UrbanBlue-System hilft Ihnen, das ökologische Gleichgewicht und das Wohlbefinden von Tieren und Pflanzen in hochtechnisierten Farmen zu erhalten.",
        screen_title_2: "Benachrichtigt werden",
        screen_desc_2: "Ihr virtueller Assistent weist auf mögliche Unregelmäßigkeiten hin und warnt Sie, bevor ein Schaden entsteht.",
        screen_title_3: "Helfende Hand",
        screen_desc_3: "Ihr neuer digitaler Freund bietet Ihnen eine helfende Hand, um erkannte Probleme rechtzeitig zu beheben.",
        screen_title_4: "Zusammenarbeit",
        screen_desc_4: "Falls etwas die Aufmerksamkeit anderer erfordert, informieren Sie Ihr Team sofort mit einem einfachen Ein-Klick-Alarm.",
        screen_title_5: "Lassen Sie mich helfen",
        screen_desc_5: "Erlauben Sie dem UrbanBlue-Assistenten, Sie über mögliche Unregelmäßigkeiten und Aktualisierungen des Systemstatus zu informieren.",
        give_perm: "Erlaubnis erteilen",
        next: "Weiter",
        validation_email: "Das E-Mail-Feld darf nicht leer sein.",
        validation_password: "Das Passwortfeld darf nicht leer sein.",
        slogan: "Intelligence working alongside.",
        email_placeholder: "Ihre E-Mail-Adresse",
        pass_placeholder: "Ihr Passwort",
        LogIn: "Anmelden",
        Loading: "WIRD GELADEN",
        forget_pass: "Passwort vergessen?",
        no_account: "Sie haben noch kein Konto?",
        contact: "Kontakt aufnehmen",
        password: "Kennwort",
        dashboard_title: "Status-Übersicht",
        Important: "Wichtig",
        Other: "Weitere",
        More: "Andere",
        More_Desc: "Verwenden Sie diese Option, um einen Kommentar zu schreiben.",
        dashboard_desc: "Die überwachten Bereiche und Systeme funktionieren wie erwartet.",
        dashboard_note: "Hinweis: Sie erhalten hier Benachrichtigungen und Aktualisierungen, falls etwas dringend Ihrer Aufmerksamkeit bedarf.",
        time_escalate: "Potentieller Schaden in",
        time_action: "Verbleibende Zeit, die Situation zu bereinigen",
        time_watchlist: "Veränderung erwartet innert",
        sec: "Sek.",
        hide: "Ausblenden",
        show: "Anzeigen",
        search: "Nach einer Situation, einem Ereignistyp oder einem Status suchen.",
        hours_ago: "Stunden her",
        mins_ago: "Minuten her",
        location: "ORT",
        detail_screen_action_title: "Bitte wählen oder ergänzen Sie die erledigten Massnahmen.",
        img: "BILD",
        add_pic: "Bild hinzufügen",
        alarm: "FEHLALARM",
        alarm_desc: "Bitte markieren im Falle eines Fehlalarms.",
        resolve: "Problem gelöst",
        req_alert_title: "WELCHE SITUATION MUSS GELÖST WERDEN?",
        req_alert_msg_placeholder: "Bitte geben Sie an, warum Sie das Team alarmieren, und fügen Sie, wenn möglich, ein Bild des Sachverhalts bei. Zum Beispiel: Ich kann die Angelegenheit nicht allein bewältigen, die getroffenen Massnahmen lösen das Problem nicht, es ist etwas kaputt, das repariert werden muss, usw.",
        confirm: "Bestätigen",
        alert_team: "Unterstützung anfordern",
        req_res_title: "WIE WURDE DAS PROBLEM GELÖST?",
        req_res_placeholder: "Bitte beschreiben Sie kurz, was Sie getan haben, um die Situation zu verbessern.",
        req_esc_title: "WELCHE SITUATION MUSS GELÖST WERDEN?",
        req_esc_desc: "Bitte geben Sie an, warum Sie das Team alarmieren, und fügen Sie, wenn möglich, ein Bild des Sachverhalts bei. Zum Beispiel: Ich kann die Angelegenheit nicht allein bewältigen, die getroffenen Massnahmen lösen das Problem nicht, es ist etwas kaputt, das repariert werden muss, usw.",
        logout_title: "Möchten Sie sich abmelden?",
        logout_desc: "Wir können Sie nicht mit Dingen benachrichtigen, die Ihre Aufmerksamkeit benötigen, wenn Sie das tun.",
        log_out: "Abmelden",
        cancel: "Abbrechen",
        history: "Historie",
        recover_desc: "Bitte geben Sie Ihre E-Mail-Adresse eingeben um E-Mail zur Wiederherstellung Ihres Kontos zu erhalten.",
        recover_mail: "Wiederherstellungs-Mail anfordern",
        action_req: "Maßnahmen erforderlich",
        escalated: "Eskaliert",
        watchlist: "Beobachtungsliste",
        action_perf: "Durchgeführte Maßnahmen",
        active_opp: "Aktiver Betrieb",
        default_op: "Standardmäßiger Betrieb",
        inactive: "Inaktiv",
        active: "Aktiviert",
        comment: "Kommentieren",
        change_ongoing: "Änderung Laufend",
        net_error: "Es ist ein Fehler aufgetreten.",
        invalid_add: "E-Mail oder Passwort sind nicht korrekt.",
        other_desc: "Derzeit gibt es hier nichts zu sehen",
        measure: "Messungen",
        current: "Aktuell",
        sensor_title: "Sensoren Übersicht"
    },
    fr: {
        screen_title_1: "Persönlicher Assistent",
        screen_desc_1: "Das UrbanBlue-System hilft Ihnen, das ökologische Gleichgewicht und das Wohlbefinden von Tieren und Pflanzen in hochtechnisierten Farmen zu erhalten.",
        screen_title_2: "Benachrichtigt werden",
        screen_desc_2: "Ihr virtueller Assistent weist auf mögliche Unregelmäßigkeiten hin und warnt Sie, bevor ein Schaden entsteht.",
        screen_title_3: "Helfende Hand",
        screen_desc_3: "Ihr neuer digitaler Freund bietet Ihnen eine helfende Hand, um erkannte Probleme rechtzeitig zu beheben.",
        screen_title_4: "Zusammenarbeit",
        screen_desc_4: "Falls etwas die Aufmerksamkeit anderer erfordert, informieren Sie Ihr Team sofort mit einem einfachen Ein-Klick-Alarm.",
        screen_title_5: "Lassen Sie mich helfen",
        screen_desc_5: "Erlauben Sie dem UrbanBlue-Assistenten, Sie über mögliche Unregelmäßigkeiten und Aktualisierungen des Systemstatus zu informieren.",
        give_perm: "Erlaubnis erteilen",
        next: "Weiter",
        validation_email: "Das E-Mail-Feld darf nicht leer sein.",
        validation_password: "Das Passwortfeld darf nicht leer sein.",
        slogan: "Intelligence working alongside.",
        email_placeholder: "Ihre E-Mail-Adresse",
        pass_placeholder: "Ihr Passwort",
        LogIn: "Anmelden",
        Loading: "WIRD GELADEN",
        forget_pass: "Passwort vergessen?",
        no_account: "Sie haben noch kein Konto?",
        contact: "Kontakt aufnehmen",
        password: "Kennwort",
        dashboard_title: "Status-Übersicht",
        Important: "Wichtig",
        Other: "Weitere",
        More: "Andere",
        More_Desc: "Verwenden Sie diese Option, um einen Kommentar zu schreiben.",
        dashboard_desc: "Die überwachten Bereiche und Systeme funktionieren wie erwartet.",
        dashboard_note: "Hinweis: Sie erhalten hier Benachrichtigungen und Aktualisierungen, falls etwas dringend Ihrer Aufmerksamkeit bedarf.",
        time_escalate: "Potentieller Schaden in",
        time_action: "Verbleibende Zeit, die Situation zu bereinigen",
        time_watchlist: "Veränderung erwartet innert",
        sec: "Sek.",
        hide: "Ausblenden",
        show: "Anzeigen",
        search: "Nach einer Situation, einem Ereignistyp oder einem Status suchen.",
        hours_ago: "Stunden her",
        mins_ago: "Minuten her",
        location: "ORT",
        detail_screen_action_title: "Bitte wählen oder ergänzen Sie die erledigten Massnahmen.",
        img: "BILD",
        add_pic: "Bild hinzufügen",
        alarm: "FEHLALARM",
        alarm_desc: "Bitte markieren im Falle eines Fehlalarms.",
        resolve: "Problem gelöst",
        req_alert_title: "WELCHE SITUATION MUSS GELÖST WERDEN?",
        req_alert_msg_placeholder: "Bitte geben Sie an, warum Sie das Team alarmieren, und fügen Sie, wenn möglich, ein Bild des Sachverhalts bei. Zum Beispiel: Ich kann die Angelegenheit nicht allein bewältigen, die getroffenen Massnahmen lösen das Problem nicht, es ist etwas kaputt, das repariert werden muss, usw.",
        confirm: "Bestätigen",
        alert_team: "Unterstützung anfordern",
        req_res_title: "WIE WURDE DAS PROBLEM GELÖST?",
        req_res_placeholder: "Bitte beschreiben Sie kurz, was Sie getan haben, um die Situation zu verbessern.",
        req_esc_title: "WELCHE SITUATION MUSS GELÖST WERDEN?",
        req_esc_desc: "Bitte geben Sie an, warum Sie das Team alarmieren, und fügen Sie, wenn möglich, ein Bild des Sachverhalts bei. Zum Beispiel: Ich kann die Angelegenheit nicht allein bewältigen, die getroffenen Massnahmen lösen das Problem nicht, es ist etwas kaputt, das repariert werden muss, usw.",
        logout_title: "Möchten Sie sich abmelden?",
        logout_desc: "Wir können Sie nicht mit Dingen benachrichtigen, die Ihre Aufmerksamkeit benötigen, wenn Sie das tun.",
        log_out: "Abmelden",
        cancel: "Abbrechen",
        history: "Historie",
        recover_desc: "Bitte geben Sie Ihre E-Mail-Adresse eingeben um E-Mail zur Wiederherstellung Ihres Kontos zu erhalten.",
        recover_mail: "Wiederherstellungs-Mail anfordern",
        action_req: "Maßnahmen erforderlich",
        escalated: "Eskaliert",
        watchlist: "Beobachtungsliste",
        action_perf: "Durchgeführte Maßnahmen",
        active_opp: "Aktiver Betrieb",
        default_op: "Standardmäßiger Betrieb",
        inactive: "Inaktiv",
        active: "Aktiviert",
        comment: "Kommentieren",
        change_ongoing: "Änderung Laufend",
        net_error: "Es ist ein Fehler aufgetreten.",
        invalid_add: "E-Mail oder Passwort sind nicht korrekt.",
        other_desc: "Derzeit gibt es hier nichts zu sehen",
        measure: "Messungen",
        current: "Aktuell",
        sensor_title: "Sensoren Übersicht"
    }
});